-- Companion PostgreSQL baseline generated from the post-#27 SQLite contract.
-- Phase A only: no runtime selector, no dual write, no production cutover.
-- Times are typed as timestamptz; JSON documents are typed as jsonb.

CREATE TABLE turn_results (turn_id text PRIMARY KEY,response text NOT NULL,created_at timestamptz NOT NULL);
CREATE TABLE notes (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,idempotency_key text NOT NULL,user_id text NOT NULL DEFAULT '',content text NOT NULL,created_at timestamptz NOT NULL);
CREATE INDEX idx_notes_user ON notes(user_id,id DESC);
CREATE TABLE expenses (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,idempotency_key text NOT NULL,user_id text NOT NULL DEFAULT '',amount_vnd bigint NOT NULL CHECK(amount_vnd>0),category text NOT NULL,description text NOT NULL,occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL);
CREATE INDEX idx_expenses_user_time ON expenses(user_id,occurred_at);
CREATE TABLE journal_entries (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,idempotency_key text NOT NULL,user_id text NOT NULL DEFAULT '',content text NOT NULL,occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL);
CREATE INDEX idx_journal_user_time ON journal_entries(user_id,occurred_at);
CREATE TABLE reminders (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,idempotency_key text NOT NULL,user_id text NOT NULL DEFAULT '',device_id text NOT NULL DEFAULT '',kind text NOT NULL DEFAULT 'reminder' CHECK(kind IN ('reminder','timer')),title text NOT NULL,fire_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'pending',attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz,paused_remaining_seconds bigint NOT NULL DEFAULT 0,created_at timestamptz NOT NULL);
CREATE INDEX idx_reminders_due ON reminders(status,next_attempt_at,fire_at);
CREATE INDEX idx_reminders_owner ON reminders(user_id,device_id,status,fire_at);
CREATE TABLE conversation_messages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,turn_key text NOT NULL,user_id text NOT NULL DEFAULT '',thread_id text NOT NULL DEFAULT 'default',role text NOT NULL CHECK(role IN ('user','assistant')),content text NOT NULL,created_at timestamptz NOT NULL,UNIQUE(turn_key,role));
CREATE INDEX idx_conversation_scope ON conversation_messages(user_id,thread_id,id DESC);
CREATE TABLE budgets (user_id text NOT NULL DEFAULT '',period text NOT NULL,limit_vnd bigint NOT NULL CHECK(limit_vnd>=0),updated_at timestamptz NOT NULL,PRIMARY KEY(user_id,period));
CREATE TABLE voice_memos (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,idempotency_key text NOT NULL,user_id text NOT NULL DEFAULT '',device_id text NOT NULL DEFAULT '',path text NOT NULL,transcript text NOT NULL DEFAULT '',duration_ms bigint NOT NULL CHECK(duration_ms>=0),created_at timestamptz NOT NULL);
CREATE INDEX idx_voice_memos_owner ON voice_memos(user_id,device_id,id DESC);
CREATE TABLE idempotency_records (actor_id text NOT NULL,operation text NOT NULL,idempotency_key text NOT NULL,request_hash text NOT NULL CHECK(request_hash ~ '^[0-9a-f]{64}$'),outcome_json jsonb NOT NULL,created_at timestamptz NOT NULL,PRIMARY KEY(actor_id,operation,idempotency_key));
CREATE TABLE legacy_idempotency_reservations (operation text NOT NULL,idempotency_key text NOT NULL,source_table text NOT NULL,created_at timestamptz NOT NULL,PRIMARY KEY(operation,idempotency_key));
CREATE TABLE memories (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id text NOT NULL,memory_key text NOT NULL,kind text NOT NULL,value text NOT NULL,valid_from timestamptz NOT NULL,valid_to timestamptz,source text NOT NULL,confidence double precision NOT NULL DEFAULT 1,embedding jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL,deleted_at timestamptz);
CREATE INDEX idx_memories_current ON memories(user_id,memory_key,valid_to,deleted_at);
CREATE INDEX idx_memories_user_time ON memories(user_id,valid_from DESC);
CREATE TABLE memory_vectors (memory_id bigint PRIMARY KEY REFERENCES memories(id) ON DELETE CASCADE,user_id text NOT NULL,embedding jsonb NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX idx_memory_vectors_user ON memory_vectors(user_id,memory_id);
CREATE TABLE device_twins (device_id text PRIMARY KEY,user_id text NOT NULL,desired_json jsonb NOT NULL DEFAULT '{}'::jsonb,desired_version bigint NOT NULL DEFAULT 0,reported_json jsonb NOT NULL DEFAULT '{}'::jsonb,reported_version bigint NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL);
CREATE TABLE config_overrides (scope_type text NOT NULL,scope_id text NOT NULL,config_json jsonb NOT NULL DEFAULT '{}'::jsonb,version bigint NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL,PRIMARY KEY(scope_type,scope_id));
CREATE TABLE config_generation (id integer PRIMARY KEY CHECK(id=1),version bigint NOT NULL);
INSERT INTO config_generation(id,version) VALUES(1,1);
CREATE TABLE feature_flags (key text PRIMARY KEY,enabled boolean NOT NULL DEFAULT false,rollout integer NOT NULL DEFAULT 100 CHECK(rollout BETWEEN 0 AND 100),required_plan text NOT NULL DEFAULT '',variants_json jsonb NOT NULL DEFAULT '{}'::jsonb,lifecycle text NOT NULL DEFAULT 'released',owner text NOT NULL DEFAULT '',expires_at timestamptz,updated_at timestamptz NOT NULL);
CREATE TABLE entitlements (subject_type text NOT NULL DEFAULT 'user',subject_id text NOT NULL,entitlement text NOT NULL,enabled boolean NOT NULL DEFAULT true,expires_at timestamptz,updated_at timestamptz NOT NULL,PRIMARY KEY(subject_type,subject_id,entitlement));
CREATE TABLE device_credentials (device_id text PRIMARY KEY,user_id text NOT NULL,tenant_id text NOT NULL DEFAULT '',plan text NOT NULL DEFAULT '',token_sha256 text NOT NULL CHECK(token_sha256 ~ '^[0-9a-f]{64}$'),status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL,rotated_at timestamptz NOT NULL);
CREATE TABLE outbox (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id text NOT NULL UNIQUE,source text NOT NULL,event_type text NOT NULL,subject text NOT NULL DEFAULT '',user_id text NOT NULL DEFAULT '',data_json jsonb NOT NULL DEFAULT '{}'::jsonb,occurred_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'pending',attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL,last_error text NOT NULL DEFAULT '');
CREATE INDEX idx_outbox_dispatch ON outbox(status,next_attempt_at,id);
CREATE TABLE market_watches (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,idempotency_key text NOT NULL,user_id text NOT NULL,device_id text NOT NULL,provider text NOT NULL,symbol text NOT NULL,currency text NOT NULL,operator text NOT NULL CHECK(operator IN ('<','<=','>','>=')),threshold double precision NOT NULL,enabled boolean NOT NULL DEFAULT true,last_state boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL);
CREATE INDEX idx_market_watches_enabled ON market_watches(enabled,provider,symbol);
CREATE TABLE firmware_releases (metadata_version bigint PRIMARY KEY,version text NOT NULL,channel text NOT NULL,board text NOT NULL,protocol_min integer NOT NULL,security_version integer NOT NULL,url text NOT NULL,sha256 text NOT NULL CHECK(sha256 ~ '^[0-9a-f]{64}$'),size bigint NOT NULL CHECK(size>=0),expires_at timestamptz NOT NULL,signature text NOT NULL DEFAULT '',manifest_json jsonb NOT NULL,created_at timestamptz NOT NULL);
CREATE INDEX idx_firmware_lookup ON firmware_releases(channel,board,metadata_version DESC);
CREATE TABLE llm_usage (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id text NOT NULL DEFAULT '',device_id text NOT NULL DEFAULT '',provider text NOT NULL,model text NOT NULL,prompt_version text NOT NULL,prompt_tokens bigint NOT NULL CHECK(prompt_tokens>=0),completion_tokens bigint NOT NULL CHECK(completion_tokens>=0),total_tokens bigint NOT NULL CHECK(total_tokens>=0),created_at timestamptz NOT NULL);
CREATE TABLE privacy_policies (user_id text PRIMARY KEY,save_voice_audio boolean NOT NULL DEFAULT false,long_term_memory_enabled boolean NOT NULL DEFAULT false,conversation_retention_days integer NOT NULL DEFAULT 0 CHECK(conversation_retention_days BETWEEN 0 AND 3650),voice_memo_retention_days integer NOT NULL DEFAULT 0 CHECK(voice_memo_retention_days BETWEEN 0 AND 3650),memory_retention_days integer NOT NULL DEFAULT 0 CHECK(memory_retention_days BETWEEN 0 AND 3650),updated_at timestamptz NOT NULL);
CREATE TABLE feature_modules (id text PRIMARY KEY,version bigint NOT NULL,lifecycle text NOT NULL,execution text NOT NULL,manifest_json jsonb NOT NULL,updated_at timestamptz NOT NULL);

CREATE OR REPLACE FUNCTION companion_outbox_expense() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP='DELETE' THEN
    INSERT INTO outbox(event_id,source,event_type,subject,user_id,data_json,occurred_at,next_attempt_at) VALUES(gen_random_uuid()::text,'/companion/domain','expense.deleted','expense/'||OLD.id,OLD.user_id,jsonb_build_object('id',OLD.id),clock_timestamp(),clock_timestamp()); RETURN OLD;
  ELSIF TG_OP='UPDATE' THEN
    INSERT INTO outbox(event_id,source,event_type,subject,user_id,data_json,occurred_at,next_attempt_at) VALUES(gen_random_uuid()::text,'/companion/domain','expense.updated','expense/'||NEW.id,NEW.user_id,jsonb_build_object('id',NEW.id,'amount_vnd',NEW.amount_vnd,'category',NEW.category),clock_timestamp(),clock_timestamp()); RETURN NEW;
  END IF;
  INSERT INTO outbox(event_id,source,event_type,subject,user_id,data_json,occurred_at,next_attempt_at) VALUES(gen_random_uuid()::text,'/companion/domain','expense.created','expense/'||NEW.id,NEW.user_id,jsonb_build_object('id',NEW.id,'amount_vnd',NEW.amount_vnd,'category',NEW.category),clock_timestamp(),clock_timestamp()); RETURN NEW;
END $$;
CREATE TRIGGER trg_expenses_ai AFTER INSERT ON expenses FOR EACH ROW EXECUTE FUNCTION companion_outbox_expense();
CREATE TRIGGER trg_expenses_au AFTER UPDATE ON expenses FOR EACH ROW EXECUTE FUNCTION companion_outbox_expense();
CREATE TRIGGER trg_expenses_ad AFTER DELETE ON expenses FOR EACH ROW EXECUTE FUNCTION companion_outbox_expense();
CREATE OR REPLACE FUNCTION companion_outbox_budget() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO outbox(event_id,source,event_type,subject,user_id,data_json,occurred_at,next_attempt_at) VALUES(gen_random_uuid()::text,'/companion/domain','budget.updated','budget/'||NEW.period,NEW.user_id,jsonb_build_object('period',NEW.period,'limit_vnd',NEW.limit_vnd),clock_timestamp(),clock_timestamp()); RETURN NEW; END $$;
CREATE TRIGGER trg_budgets_ai AFTER INSERT ON budgets FOR EACH ROW EXECUTE FUNCTION companion_outbox_budget();
CREATE TRIGGER trg_budgets_au AFTER UPDATE ON budgets FOR EACH ROW EXECUTE FUNCTION companion_outbox_budget();
CREATE OR REPLACE FUNCTION companion_outbox_reminder() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO outbox(event_id,source,event_type,subject,user_id,data_json,occurred_at,next_attempt_at) VALUES(gen_random_uuid()::text,'/companion/domain',NEW.kind||'.created',NEW.kind||'/'||NEW.id,NEW.user_id,jsonb_build_object('id',NEW.id,'device_id',NEW.device_id,'fire_at',NEW.fire_at),clock_timestamp(),clock_timestamp()); RETURN NEW; END $$;
CREATE TRIGGER trg_reminders_ai AFTER INSERT ON reminders FOR EACH ROW EXECUTE FUNCTION companion_outbox_reminder();
CREATE OR REPLACE FUNCTION companion_outbox_memory() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN INSERT INTO outbox(event_id,source,event_type,subject,user_id,data_json,occurred_at,next_attempt_at) VALUES(gen_random_uuid()::text,'/companion/memory','memory.created','memory/'||NEW.id,NEW.user_id,jsonb_build_object('id',NEW.id,'key',NEW.memory_key,'kind',NEW.kind),clock_timestamp(),clock_timestamp()); RETURN NEW; END $$;
CREATE TRIGGER trg_memories_ai AFTER INSERT ON memories FOR EACH ROW EXECUTE FUNCTION companion_outbox_memory();
CREATE OR REPLACE FUNCTION companion_outbox_twin() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.desired_version IS DISTINCT FROM OLD.desired_version THEN INSERT INTO outbox(event_id,source,event_type,subject,user_id,data_json,occurred_at,next_attempt_at) VALUES(gen_random_uuid()::text,'/companion/control','device.config.updated','device/'||NEW.device_id,NEW.user_id,jsonb_build_object('device_id',NEW.device_id,'version',NEW.desired_version),clock_timestamp(),clock_timestamp()); END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_twins_au AFTER UPDATE ON device_twins FOR EACH ROW EXECUTE FUNCTION companion_outbox_twin();
