package pgstore

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"companion-server/internal/domain"
	"companion-server/internal/events"
	"companion-server/internal/market"
	"companion-server/internal/server"
	"github.com/jackc/pgx/v5"
)

func (s *Store) PendingOutbox(ctx context.Context, now time.Time, limit int) ([]events.Event,error){
	if limit<=0||limit>500{limit=100};tx,err:=s.pool.Begin(ctx);if err!=nil{return nil,err};defer tx.Rollback(ctx)
	rows,err:=tx.Query(ctx,`SELECT id,event_id,source,event_type,subject,user_id,data_json,occurred_at,attempts FROM outbox WHERE status='pending' AND next_attempt_at<=$1 ORDER BY id LIMIT $2 FOR UPDATE SKIP LOCKED`,now.UTC(),limit);if err!=nil{return nil,err};type row struct{id int64;e events.Event};var selected []row
	for rows.Next(){var r row;var raw []byte;if err:=rows.Scan(&r.id,&r.e.ID,&r.e.Source,&r.e.Type,&r.e.Subject,&r.e.UserID,&raw,&r.e.OccurredAt,&r.e.Attempts);err!=nil{rows.Close();return nil,err};r.e.OccurredAt=r.e.OccurredAt.UTC();if len(raw)>0{_ = json.Unmarshal(raw,&r.e.Data)};selected=append(selected,r)};if err:=rows.Err();err!=nil{rows.Close();return nil,err};rows.Close()
	if len(selected)>0{ids:=make([]int64,0,len(selected));for _,r:=range selected{ids=append(ids,r.id)};if _,err:=tx.Exec(ctx,`UPDATE outbox SET status='dispatching' WHERE id=ANY($1)`,ids);err!=nil{return nil,err}}
	if err:=tx.Commit(ctx);err!=nil{return nil,err};out:=make([]events.Event,0,len(selected));for _,r:=range selected{out=append(out,r.e)};return out,nil
}
func (s *Store) MarkOutboxSent(ctx context.Context,eventID string)error{tag,err:=s.pool.Exec(ctx,`UPDATE outbox SET status='sent',last_error='' WHERE event_id=$1 AND status='dispatching'`,eventID);if err!=nil{return err};return requireRowsChanged(tag.RowsAffected(),"outbox event")}
func (s *Store) RetryOutbox(ctx context.Context,eventID,lastError string,next time.Time)error{tag,err:=s.pool.Exec(ctx,`UPDATE outbox SET status='pending',attempts=attempts+1,last_error=$1,next_attempt_at=$2 WHERE event_id=$3 AND status='dispatching'`,strings.TrimSpace(lastError),next.UTC(),eventID);if err!=nil{return err};return requireRowsChanged(tag.RowsAffected(),"outbox event")}
func (s *Store) RecoverOutbox(ctx context.Context)error{_,err:=s.pool.Exec(ctx,`UPDATE outbox SET status='pending' WHERE status='dispatching'`);return err}

func (s *Store) CreateMarketWatch(ctx context.Context,userID,key,deviceID,provider,symbol,currency,operator string,threshold float64)(market.Watch,error){
	if err:=market.ValidateOperator(operator);err!=nil{return market.Watch{},err};provider=strings.TrimSpace(provider);symbol=strings.TrimSpace(symbol);currency=strings.TrimSpace(currency);if provider==""||symbol==""||currency==""{return market.Watch{},fmt.Errorf("provider symbol and currency required")}
	tx,err:=s.pool.Begin(ctx);if err!=nil{return market.Watch{},err};defer tx.Rollback(ctx);if err:=lockLegacyIdentity(ctx,tx,"market_watches",userID,key);err!=nil{return market.Watch{},err}
	var existing market.Watch;err=tx.QueryRow(ctx,`SELECT id,user_id,device_id,provider,symbol,currency,operator,threshold,enabled,last_state,created_at FROM market_watches WHERE user_id=$1 AND idempotency_key=$2`,owner(userID),key).Scan(&existing.ID,&existing.UserID,&existing.DeviceID,&existing.Provider,&existing.Symbol,&existing.Currency,&existing.Operator,&existing.Threshold,&existing.Enabled,&existing.LastState,&existing.CreatedAt);if err==nil{_ = tx.Commit(ctx);existing.CreatedAt=existing.CreatedAt.UTC();return existing,nil};if err!=pgx.ErrNoRows{return market.Watch{},err}
	created:=time.Now().UTC();var id int64;err=tx.QueryRow(ctx,`INSERT INTO market_watches(idempotency_key,user_id,device_id,provider,symbol,currency,operator,threshold,enabled,last_state,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,true,false,$9) RETURNING id`,key,owner(userID),strings.TrimSpace(deviceID),provider,symbol,currency,operator,threshold,created).Scan(&id);if err!=nil{return market.Watch{},err};if err:=tx.Commit(ctx);err!=nil{return market.Watch{},err};return market.Watch{ID:id,UserID:owner(userID),DeviceID:strings.TrimSpace(deviceID),Provider:provider,Symbol:symbol,Currency:currency,Operator:operator,Threshold:threshold,Enabled:true,CreatedAt:created},nil
}
func (s *Store) ListMarketWatches(ctx context.Context,userID,deviceID string,limit int)([]market.Watch,error){query:=`SELECT id,user_id,device_id,provider,symbol,currency,operator,threshold,enabled,last_state,created_at FROM market_watches WHERE user_id=$1`;args:=[]any{owner(userID)};if strings.TrimSpace(deviceID)!=""{query+=` AND (device_id=$2 OR device_id='') ORDER BY id DESC LIMIT $3`;args=append(args,strings.TrimSpace(deviceID),boundedLimit(limit))}else{query+=` ORDER BY id DESC LIMIT $2`;args=append(args,boundedLimit(limit))};rows,err:=s.pool.Query(ctx,query,args...);if err!=nil{return nil,err};defer rows.Close();return scanWatches(rows)}
func scanWatches(rows pgx.Rows)([]market.Watch,error){var out []market.Watch;for rows.Next(){var w market.Watch;if err:=rows.Scan(&w.ID,&w.UserID,&w.DeviceID,&w.Provider,&w.Symbol,&w.Currency,&w.Operator,&w.Threshold,&w.Enabled,&w.LastState,&w.CreatedAt);err!=nil{return nil,err};w.CreatedAt=w.CreatedAt.UTC();out=append(out,w)};return out,rows.Err()}
func (s *Store) DeleteMarketWatch(ctx context.Context,userID string,id int64)error{tag,err:=s.pool.Exec(ctx,`DELETE FROM market_watches WHERE id=$1 AND user_id=$2`,id,owner(userID));if err!=nil{return err};return requireRowsChanged(tag.RowsAffected(),"market watch")}
func (s *Store) EnabledMarketWatches(ctx context.Context,limit int)([]market.Watch,error){rows,err:=s.pool.Query(ctx,`SELECT id,user_id,device_id,provider,symbol,currency,operator,threshold,enabled,last_state,created_at FROM market_watches WHERE enabled=true ORDER BY id LIMIT $1`,boundedLimit(limit));if err!=nil{return nil,err};defer rows.Close();return scanWatches(rows)}
func (s *Store) SetMarketWatchState(ctx context.Context,id int64,state bool)error{tag,err:=s.pool.Exec(ctx,`UPDATE market_watches SET last_state=$1 WHERE id=$2`,state,id);if err!=nil{return err};return requireRowsChanged(tag.RowsAffected(),"market watch")}
func (s *Store) TriggerMarketWatch(ctx context.Context,w market.Watch,title string,now time.Time)(bool,error){tx,err:=s.pool.Begin(ctx);if err!=nil{return false,err};defer tx.Rollback(ctx);var enabled,last bool;if err:=tx.QueryRow(ctx,`SELECT enabled,last_state FROM market_watches WHERE id=$1 FOR UPDATE`,w.ID).Scan(&enabled,&last);err!=nil{return false,err};if !enabled||last{return false,nil};key:=fmt.Sprintf("market-watch:%d:%d",w.ID,now.Unix());if _,err:=tx.Exec(ctx,`INSERT INTO reminders(idempotency_key,user_id,device_id,kind,title,fire_at,status,attempts,next_attempt_at,paused_remaining_seconds,created_at) VALUES($1,$2,$3,'reminder',$4,$5,'pending',0,NULL,0,$5)`,key,owner(w.UserID),strings.TrimSpace(w.DeviceID),strings.TrimSpace(title),now.UTC());err!=nil{return false,err};if _,err:=tx.Exec(ctx,`UPDATE market_watches SET last_state=true WHERE id=$1`,w.ID);err!=nil{return false,err};return true,tx.Commit(ctx)}

func (s *Store) RecoverDispatchingReminders(ctx context.Context)(int64,error){tag,err:=s.pool.Exec(ctx,`UPDATE reminders SET status='pending',next_attempt_at=NULL WHERE status='dispatching'`);if err!=nil{return 0,err};return tag.RowsAffected(),nil}
func (s *Store) ClaimDueReminders(ctx context.Context,now time.Time,limit int)([]domain.ScheduledItem,error){if limit<=0||limit>100{limit=32};tx,err:=s.pool.Begin(ctx);if err!=nil{return nil,err};defer tx.Rollback(ctx);rows,err:=tx.Query(ctx,`SELECT id,user_id,device_id,kind,title,fire_at,status,attempts,COALESCE(next_attempt_at,'epoch'::timestamptz),next_attempt_at IS NOT NULL,paused_remaining_seconds FROM reminders WHERE (status='pending' AND fire_at<=$1) OR (status='sent' AND next_attempt_at IS NOT NULL AND next_attempt_at<=$1) ORDER BY COALESCE(next_attempt_at,fire_at),id LIMIT $2 FOR UPDATE SKIP LOCKED`,now.UTC(),limit);if err!=nil{return nil,err};items,err:=scanScheduled(rows);rows.Close();if err!=nil{return nil,err};if len(items)>0{ids:=make([]int64,0,len(items));for _,item:=range items{ids=append(ids,item.ID)};if _,err:=tx.Exec(ctx,`UPDATE reminders SET status='dispatching' WHERE id=ANY($1)`,ids);err!=nil{return nil,err}};if err:=tx.Commit(ctx);err!=nil{return nil,err};return items,nil}
func (s *Store) MarkReminderSent(ctx context.Context,id int64,next time.Time)error{tag,err:=s.pool.Exec(ctx,`UPDATE reminders SET status='sent',attempts=attempts+1,next_attempt_at=$1 WHERE id=$2 AND status='dispatching'`,next.UTC(),id);if err!=nil{return err};return requireRowsChanged(tag.RowsAffected(),"reminder")}
func (s *Store) ReleaseReminder(ctx context.Context,id int64)error{tag,err:=s.pool.Exec(ctx,`UPDATE reminders SET status='pending',next_attempt_at=NULL WHERE id=$1 AND status='dispatching'`,id);if err!=nil{return err};return requireRowsChanged(tag.RowsAffected(),"reminder")}
func (s *Store) AcknowledgeReminder(ctx context.Context,userID,deviceID string,id int64)error{tag,err:=s.pool.Exec(ctx,`UPDATE reminders SET status='fired',next_attempt_at=NULL WHERE id=$1 AND user_id=$2 AND (device_id=$3 OR device_id='') AND status IN ('dispatching','sent')`,id,owner(userID),strings.TrimSpace(deviceID));if err!=nil{return err};return requireRowsChanged(tag.RowsAffected(),"reminder")}
func (s *Store) NextReminder(ctx context.Context,userID,deviceID string,now time.Time)(domain.ScheduledItem,bool,error){var item domain.ScheduledItem;var next time.Time;var hasNext bool;err:=s.pool.QueryRow(ctx,`SELECT id,user_id,device_id,kind,title,fire_at,status,attempts,COALESCE(next_attempt_at,'epoch'::timestamptz),next_attempt_at IS NOT NULL,paused_remaining_seconds FROM reminders WHERE user_id=$1 AND (device_id=$2 OR device_id='') AND status IN ('pending','sent') AND fire_at>=$3 ORDER BY fire_at,id LIMIT 1`,owner(userID),strings.TrimSpace(deviceID),now.UTC()).Scan(&item.ID,&item.UserID,&item.DeviceID,&item.Kind,&item.Title,&item.FireAt,&item.Status,&item.Attempts,&next,&hasNext,&item.PausedRemainingSeconds);if err==pgx.ErrNoRows{return item,false,nil};if err!=nil{return item,false,err};item.FireAt=item.FireAt.UTC();if hasNext{next=next.UTC();item.NextAttempt=&next};return item,true,nil}

var _ events.Outbox = (*Store)(nil)
var _ market.WatchRepository = (*Store)(nil)
var _ server.SchedulerRepository = (*Store)(nil)
